# --- !Ups

CREATE TABLE sdec_staff
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid  VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL
);

CREATE TABLE sdec_team
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    srs_name      VARCHAR(100) NOT NULL UNIQUE,
    is_task_based BOOLEAN DEFAULT FALSE
);

CREATE TABLE staff_role
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT      NOT NULL,
    team_id  BIGINT      NOT NULL,
    srs_role VARCHAR(20) NOT NULL CHECK ( srs_role IN ('supervisor', 'caseworker')),
    CONSTRAINT fk_staff_role FOREIGN KEY (staff_id) REFERENCES sdec_staff (id),
    CONSTRAINT fk_team_role FOREIGN KEY (team_id) REFERENCES sdec_team (id),
    CONSTRAINT uq_staff_team UNIQUE (staff_id, team_id)
);

CREATE TABLE sdec_recipient
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_id  VARCHAR(50)  DEFAULT NULL,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) DEFAULT NULL,
    nino         VARCHAR(20)  NOT NULL
);


CREATE TABLE sdec_thread
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference              VARCHAR(100)  NOT NULL UNIQUE,
    status                 VARCHAR(20)   NOT NULL,
    created_by             BIGINT        NOT NULL,
    created_timestamp      TIMESTAMP     NOT NULL,
    last_updated_timestamp TIMESTAMP     NOT NULL,
    thread_expiry_date     DATE          NOT NULL,
    case_reference         VARCHAR(100),
    recipient_id           BIGINT DEFAULT NULL,
    email                  VARCHAR(255)  NOT NULL,
    nino                   VARCHAR(20),
    message                VARCHAR(4000) NOT NULL,
    required_by            DATE   DEFAULT NULL,

    CONSTRAINT fk_thread_staff FOREIGN KEY (created_by) REFERENCES sdec_staff (id),
    CONSTRAINT fk_thread_recipient FOREIGN KEY (recipient_id) REFERENCES sdec_recipient (id)
);


# --- !Downs

DROP TABLE sdec_thread;
DROP TABLE sdec_recipient;
DROP TABLE staff_role;
DROP TABLE sdec_team;
DROP TABLE sdec_staff;