# --- !Ups

CREATE TABLE sdec_thread
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference              VARCHAR(100) NOT NULL UNIQUE,
    status                 VARCHAR(20)  NOT NULL,
    created_timestamp      TIMESTAMP    NOT NULL,
    last_updated_timestamp TIMESTAMP    NOT NULL,
    thread_expiry_date     DATE         NOT NULL,
    case_reference         VARCHAR(100) NOT NULL,
    email                  VARCHAR(255) NOT NULL,
    nino                   VARCHAR(20)  NOT NULL
);

CREATE TABLE sdec_thread_details
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sdec_thread_id BIGINT        NOT NULL,
    message        VARCHAR(4000) NOT NULL,
    required_by    DATE          NOT NULL,

    CONSTRAINT fk_sdec_thread_details_thread
        FOREIGN KEY (sdec_thread_id)
            REFERENCES sdec_thread (id)
);

CREATE INDEX idx_sdec_thread_details_thread_id
    ON sdec_thread_details (sdec_thread_id);

CREATE TABLE sdec_recipient
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sdec_thread_id            BIGINT       NOT NULL,
    first_name                VARCHAR(100) NOT NULL,
    last_name                 VARCHAR(100) NOT NULL,
    email                     VARCHAR(255) NOT NULL,
    phone_number              VARCHAR(50)  NOT NULL,
    national_insurance_number VARCHAR(20)  NOT NULL,

    CONSTRAINT fk_sdec_recipient_thread
        FOREIGN KEY (sdec_thread_id)
            REFERENCES sdec_thread (id)
);

CREATE INDEX idx_sdec_recipient_thread_id
    ON sdec_recipient (sdec_thread_id);

# --- !Downs

DROP TABLE sdec_recipient;
DROP TABLE sdec_thread_details;
DROP TABLE sdec_thread;